{allowAdjacentFDs: true, allowAdjacentTextFDs: false, analysis: null, autoCreateXML: false,
  autoRun: true, autoRunHigh: 3, breakSequenceAt: 0d0a, breakSequences: false, buildDFAViaRegEx: true,
  calculateMaxMessageLength: false, checkConsistencyOnMerge: false, collapseFinals: true,
  configFile: config.yml, considerOneMessageAsConstant: false, constantsAreCaseSensitive: true,
  danglingRegEx: true, debug: false, dumpFile: /home/daubersc/result, ethOffset: 14,
  fastReverXStage1: false, fieldDelimiter: null, flowsMustBeStrictlyAlternating: true,
  format: bro, gapScore: 1, gnuplotFile: null, graph: false, highlightOutlier: true,
  inputFile: /home/daubersc/result/ftp_big_10000_4, interactive: true, lastMessageIsDirectlyFinal: false,
  loadClientAndServerParts: true, matchScore: 1, maxDistinctFDValues: 35, maxFlows: 10000,
  maxMessageLengthConfidenceInterval: 0.95, maxMessagePrefix: 2048, mergeSimilarClusters: true,
  messageDelimiter: null, minDistinctFDValues: 1, minWordLength: 3, minimizeDFA: false,
  minimumClusterSize: 5, mismatchScore: 1, multipleChoiceChooserClass: MostSpecialFirstChooser,
  nativeReverXStage1: true, numOfTestEntries: 10000, onlyUniq: false, performReverXMinimization: true,
  performReverXStage2: false, printMessagesOfCluster: false, pruneBelowLinkScore: 1,
  pruneDFAOutliers: false, requireTotalLengthChangeForLengthField: false, sessionIDOnlyWithBinary: true,
  sessionIDOnlyWithClustersWithMoreThanOneMessage: true, setAbsoluteMax: 5, setPercentageThreshold: 0.3,
  strictMergeOfOutgoingEdges: true, testFile: /home/daubersc/result/ftp_big_10000_0,
  testbasename: /home/daubersc/result/ftp_big_10000, textBased: false, weight: 1.0,
  weightEdges: true}
