{allowAdjacentFDs: true, allowAdjacentTextFDs: false, analysis: null, autoCreateXML: false, autoRunHigh: 91,
  breakSequenceAt: 0d0a, breakSequences: false, buildDFAViaRegEx: false, calculateMaxMessageLength: false,
  checkConsistencyOnMerge: false, collapseFinals: true, configFile: config.yml, considerOneMessageAsConstant: true,
  constantsAreCaseSensitive: true, danglingRegEx: true, debug: false, dumpFile: /home/daubersc/result/,
  ethOffset: 14, fastReverXStage1: false, fieldDelimiter: null, flowsMustBeStrictlyAlternating: true,
  format: bro, gapScore: 1, gnuplotFile: null, graph: false, highlightOutlier: true,
  inputFile: /home/daubersc/result/dns_1000_92, interactive: true, lastMessageIsDirectlyFinal: false,
  loadClientAndServerParts: true, matchScore: 1, maxDistinctFDValues: 10, maxFlows: 1000,
  maxMessageLengthConfidenceInterval: 0.95, maxMessagePrefix: 12, mergeSimilarClusters: true,
  messageDelimiter: null, minDistinctFDValues: 1, minWordLength: 3, minimizeDFA: false,
  minimumClusterSize: 5, mismatchScore: 1, multipleChoiceChooserClass: RandomWeightedChooser,
  nativeReverXStage1: true, numOfTestEntries: 1000, onlyUniq: false, performReverXMinimization: false,
  performReverXStage2: true, printMessagesOfCluster: false, pruneBelowLinkScore: 1,
  pruneDFAOutliers: false, requireTotalLengthChangeForLengthField: false, sessionIDOnlyWithBinary: true,
  sessionIDOnlyWithClustersWithMoreThanOneMessage: true, setAbsoluteMax: 5, setPercentageThreshold: 0.3,
  setUpperBound: 5, strictMergeOfOutgoingEdges: true, testFile: /home/daubersc/result/dns_1000_0,
  testbasename: /home/daubersc/result/dns_1000, textBased: false, weight: 1.0, weightEdges: true, autoRun: true}
