format: <bro|pcap|ascii>
onlyUniqMessages: [ False | True ]
weight: [0, 1.0]
graph: [ False | True ]
maxMessages: [0 - ...]
textBased: [ False | True ]

analysis: [PI | reverx | entropy ]

messageDelimiter: '\r\n'
fieldDelimiter: ' '
